# Generated by Django 3.0.8 on 2020-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_img', models.ImageField(upload_to='')),
                ('music_name', models.CharField(max_length=20)),
                ('prod_name', models.CharField(max_length=20)),
                ('music_desc', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TopCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='')),
                ('artist_name', models.CharField(max_length=20)),
                ('header', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
