# Generated by Django 3.0.8 on 2020-07-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopCarousel',
        ),
    ]
